env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 120
    lines: 42

  padding:
    x: 2
    y: 2

  dynamic_padding: true
  decorations: buttonless
  startup_mode: Windowed
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Fira Code

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

draw_bold_text_with_bright_colors: true

colors:
   primary:
     background: '0x0A0E14'
     foreground: '0xB3B1AD'

   normal:
     black: '0x01060E'
     red: '0xEA6C73'
     green: '0x91B362'
     yellow: '0xF9AF4F'
     blue: '0x53BDFA'
     magenta: '0xFAE994'
     cyan: '0x90E1C6'
     white: '0xC7C7C7'

   bright:
     black: '0x686868'
     red: '0xF07178'
     green: '0xC2D94C'
     yellow: '0xFFB454'
     blue: '0x59C2FF'
     magenta: '0xFFEE99'
     cyan: '0x95E6CB'
     white: '0xFFFFFF'

bell:
  animation: EaseOutExpo
  duration: 50
  color: '0x404040'
  command:
    program: osascript
    args: [-e, "beep"]

background_opacity: 0.8

debug:
  render_timer: false
  persistent_logging: true
  log_level: Warn
  print_events: false
  ref_test: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: true

  url:
    modifiers: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true
  #thickness

live_config_reload: true

shell:
   program: /usr/local/bin/fish
  #  args:
  #    - /Users/yiweiyang/.myutils/bin/alacritty-launch

enable_experimental_conpty_backend: false

alt_send_esc: true
