enable_experimental_conpty_backend = false
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0x404040"
duration = 50

[bell.command]
args = ["-e", "beep"]
program = "osascript"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x686868"
blue = "0x59C2FF"
cyan = "0x95E6CB"
green = "0xC2D94C"
magenta = "0xFFEE99"
red = "0xF07178"
white = "0xFFFFFF"
yellow = "0xFFB454"

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x90E1C6"
green = "0x91B362"
magenta = "0xFAE994"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.primary]
background = "0x0A0E14"
foreground = "0xB3B1AD"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = true
print_events = false
ref_test = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Fira Code"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 42

[window.padding]
x = 2
y = 2
